# Generated by Django 2.1.1 on 2018-09-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccessTokenId', models.CharField(max_length=255, verbose_name='アクセストークンID')),
                ('refreshTokenId', models.CharField(max_length=255, verbose_name='リフレッシュトークンID')),
                ('AccessToken', models.CharField(max_length=255, verbose_name='アクセストークン')),
                ('validTs', models.TimeField(verbose_name='有効期限')),
                ('regTs', models.TimeField(verbose_name='登録日時')),
            ],
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authId', models.CharField(max_length=255, verbose_name='認可ID')),
                ('endUserId', models.CharField(max_length=255, verbose_name='エンドユーザID')),
                ('regTs', models.TimeField(verbose_name='登録日時')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refreshTokenId', models.CharField(max_length=255, verbose_name='リフレッシュトークンID')),
                ('authId', models.CharField(max_length=255, verbose_name='認可ID')),
                ('refreshToken', models.CharField(max_length=255, verbose_name='リフレッシュトークン')),
                ('validTs', models.TimeField(verbose_name='有効期限')),
                ('regTs', models.TimeField(verbose_name='登録日時')),
            ],
        ),
    ]
