# Generated by Django 2.1.1 on 2018-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20180905_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='endUserId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ensUserId',
        ),
        migrations.AddField(
            model_name='auth',
            name='userId',
            field=models.CharField(default=1, max_length=255, verbose_name='ユーザID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=3, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(max_length=255, verbose_name='ユーザID'),
        ),
    ]
