# Generated by Django 2.1.1 on 2018-09-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20180905_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='AccessTokenId',
            field=models.CharField(max_length=255, unique=True, verbose_name='アクセストークンID'),
        ),
        migrations.AlterField(
            model_name='auth',
            name='authId',
            field=models.CharField(max_length=255, unique=True, verbose_name='認可ID'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='refreshTokenId',
            field=models.CharField(max_length=255, unique=True, verbose_name='リフレッシュトークンID'),
        ),
    ]
